version: "3.9"
services:
  javapp:
    build: ./
    network_mode: "host"
    image: gui-javapp:group_pair_name
    volumes: #Unix socket to permit to the container use the system ui client.
      - /tmp/.X11-unix:/tmp/.X11-unix 
      - /home/Facturas:/root/Facturas
    environment:
      - DISPLAY 
      - XAUTH # need to define this on the env by export XAUTH=$(auth list) to get credential key for X11.
    depends_on:
    - database
  database:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      POSTGRES_PASSWORD: Juanito7575 # change the default admin user password.
      POSTGRES_DB: testjava # change the name of the default database created.
