/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import Controlador.ControladorOrder;
import excepciones.DBConexionExcepcion;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author juancamilo
 */
public class TableOrders extends javax.swing.JFrame {

    ControladorOrder controladorOrder;
    DefaultTableModel mdOrdersTable;

    /**
     * Creates new form TableOrders
     */
    public TableOrders() throws DBConexionExcepcion {
        initComponents();
        controladorOrder = new ControladorOrder();
        String data[][] = {};
        String columnsOrderTable[] = {"Id pedido", "Fecha", "id cliente", "Nombre cliente"};
        mdOrdersTable = new DefaultTableModel(data, columnsOrderTable);
        tableOrders.setModel(mdOrdersTable);
        tableOrders.setDefaultEditor(Object.class, null);
        loadOrders();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableOrders = new javax.swing.JTable();
        loadOrdersBtn = new javax.swing.JButton();
        createOrderBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        consultProductOrderBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 128, 244));
        jLabel1.setText("Lista de Pedidos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 190, -1));

        tableOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableOrders);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 92, 510, 300));

        loadOrdersBtn.setBackground(new java.awt.Color(153, 102, 255));
        loadOrdersBtn.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        loadOrdersBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Camilo\\Documents\\Empresa-XYZ - ultimos cambios\\src\\main\\java\\imgs\\refresh.png")); // NOI18N
        loadOrdersBtn.setText("Cargar");
        loadOrdersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadOrdersBtnActionPerformed(evt);
            }
        });
        jPanel1.add(loadOrdersBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 130, -1));

        createOrderBtn.setBackground(new java.awt.Color(51, 153, 255));
        createOrderBtn.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        createOrderBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Camilo\\Documents\\Empresa-XYZ - ultimos cambios\\src\\main\\java\\imgs\\agregar-paquete.png")); // NOI18N
        createOrderBtn.setText("Crear");
        createOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createOrderBtnActionPerformed(evt);
            }
        });
        jPanel1.add(createOrderBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 130, -1));

        backBtn.setBackground(new java.awt.Color(67, 35, 248));
        backBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Camilo\\Documents\\Empresa-XYZ - ultimos cambios\\src\\main\\java\\imgs\\atras 16px.png")); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        consultProductOrderBtn.setBackground(new java.awt.Color(153, 255, 153));
        consultProductOrderBtn.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        consultProductOrderBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Camilo\\Documents\\Empresa-XYZ - ultimos cambios\\src\\main\\java\\imgs\\buscar 24px.png")); // NOI18N
        consultProductOrderBtn.setText("Consultar");
        consultProductOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultProductOrderBtnActionPerformed(evt);
            }
        });
        jPanel1.add(consultProductOrderBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 130, -1));

        jPanel2.setBackground(new java.awt.Color(0, 128, 244));
        jPanel2.setForeground(new java.awt.Color(0, 128, 244));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 680, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 680, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadOrdersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadOrdersBtnActionPerformed
        try {
            // TODO add your handling code here:
            loadOrders();
        } catch (DBConexionExcepcion ex) {
            Logger.getLogger(TableOrders.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loadOrdersBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.setVisible(false);
        VistaUser MenuPrin = null;
        try {
            MenuPrin = new VistaUser();
        } catch (DBConexionExcepcion ex) {
            Logger.getLogger(TableOrders.class.getName()).log(Level.SEVERE, null, ex);
        }
        MenuPrin.setLocationRelativeTo(null);
        MenuPrin.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void createOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createOrderBtnActionPerformed
        // TODO add your handling code here:
        FormOrder formOrder = new FormOrder();
        formOrder.setLocationRelativeTo(null);
        formOrder.setVisible(true);
    }//GEN-LAST:event_createOrderBtnActionPerformed

    private void consultProductOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultProductOrderBtnActionPerformed
        // TODO add your handling code here:
        try {
            int selected = tableOrders.getSelectedRow();
            String idOrderStr = tableOrders.getModel().getValueAt(selected, 0).toString();
            int idOrder = Integer.parseInt(idOrderStr);
            TableOrderProduct tableOrderProduct = new TableOrderProduct(idOrder);
            tableOrderProduct.setLocationRelativeTo(null);
            tableOrderProduct.setVisible(true);
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un pedido de la tabla", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (DBConexionExcepcion ex) {
            Logger.getLogger(TableOrders.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_consultProductOrderBtnActionPerformed

    private void loadOrders() throws DBConexionExcepcion {
        mdOrdersTable.setRowCount(0);
        List<String[]> orders = controladorOrder.selectOrders();
        orders.forEach(order -> mdOrdersTable.addRow(order));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TableOrders().setVisible(true);
                } catch (DBConexionExcepcion ex) {
                    Logger.getLogger(TableOrders.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton consultProductOrderBtn;
    private javax.swing.JButton createOrderBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadOrdersBtn;
    private javax.swing.JTable tableOrders;
    // End of variables declaration//GEN-END:variables
}
